/* ============================================================
   hey EU – Europakarte (erzeugt aus Polygonen, tools/mapgen.js)
   Ein Zeichen = eine Kachel vor der Skalierung.
   '.' = Meer, '_' = neutrales Land (kein Spiel-Land)
   Nicht von Hand ändern – stattdessen tools/mapgen.js anpassen
   und "node tools/mapgen.js" ausführen.
   ============================================================ */

const MAP_CHARS = {
  I: 'is', J: 'ie', U: 'uk', P: 'pt', E: 'es', a: 'ad', F: 'fr', o: 'mc',
  B: 'be', u: 'lu', N: 'nl', D: 'de', K: 'dk', V: 'no', S: 'se', M: 'fi',
  T: 'ee', L: 'lv', Y: 'lt', b: 'by', W: 'pl', C: 'cz', k: 'sk', A: 'at',
  Z: 'ch', i: 'li', n: 'si', X: 'it', s: 'sm', v: 'va', t: 'mt', Q: 'hr',
  h: 'ba', r: 'rs', m: 'me', x: 'xk', l: 'al', d: 'mk', G: 'bg', R: 'ro',
  e: 'md', y: 'ua', H: 'hu', g: 'gr', c: 'cy'
};

const EUROPE_MAP = [
  '.......................................................VVVVVVVVVVV..........................',
  '................................................VVVVVVVVVVVVVVVVVVVVVV......................',
  '........IIIII..................................VVVVVVVVVVVVVVVVVMMVVV.......................',
  '....IIIIIIIIII...............................VVVVVVVVVVVVVVVMMMMMMMVV.......................',
  '....IIIIIIIIIII.............................VVVVVVVVVVVVVMMMMMMMMMMM........................',
  '.....IIIIIIIIII............................VVVVVVVVVVVVMMMMMMMMMMMMMM.......................',
  '.....IIIIIIIII............................VVVVVVVVVSV...MMMMMMMMMMMMMM......................',
  '........IIIII.............UU..............VVVVVVVSSSS....MMMMMMMMMMMM.......................',
  '........................UUUU..............VVVVVSSSSSSS...MMMMMMMMMMMM.......................',
  '.......................UUUUU.............VVVVVSSSSSSSSS..MMMMMMMMMMMM.......................',
  '.......................UUUUUU............VVVVVSSSSSSSSS..MMMMMMMMMMM........................',
  '......................UUUUUUU............VVVVVSSSSSSSSS...MMMMMMMMMM........................',
  '......................UUUUUUU...........VVVVVVSSSSSSSS....MMMMMMMMM....................____.',
  '.......................UUUUUUU..........VVVVVVSSSSSSSS....MMMMMMMM..............___________.',
  '.......................UUUUUUU..........VVVVVVSSSSSSSS.....MMMMMM............______________.',
  '.................JJJ....UUUUUUU..........VVVVVSSSSSSSS......MMMM.............______________.',
  '..............JJJJJJ....UUUUUUUU.........VVVV.SSSSSSSS.......MM..............______________.',
  '..............JJJJJJ.....UUUUUUU..............SSSSSSS......................._______________.',
  '.............JJJJJJJJ....UUUUUUU.........KKKKK.SSSSSS......................._______________.',
  '.............JJJJJJJJ...UUUUUUUU.........KKKKK.SSSSSS.........TTTTTTTT......_______________.',
  '.............JJJJJJJ....UUUUUUUU.........KKKKK.SSSSS..........TTTTTTTT......_______________.',
  '..............JJJJJ.....UUUUUUUU.........KKKKK..SSSS..........TTTTTTTT......_______________.',
  '.................J.....UUUUUUUUU.........KKKKK................TTTTTTTT.......______________.',
  '.......................UUUUUUUU..........KKKKK...............LLLLLLLLLLLbbbbb______________.',
  '........................UUUUU........NNNNNNDDDDDDDD..........LLLLLLLLLLLbbbbb______________.',
  '..........................UU.........NNNNNNDDDDDDDDD.........LLLLLLLLLLLbbbbb______________.',
  '.....................................NNNNNNDDDDDDDDWWWWWWWWWWLLLLLLLLLLLbbbbb______________.',
  '......................................NNNNNNDDDDDDDWWWWWWWWWWWYYYYYYYYYbbbbbbb_____________.',
  '......................................NNNNNNDDDDDDWWWWWWWWWWWWYYYYYYYYYbbbbbbb_yyyyy_______.',
  '....................................BBBBBBBDDDDDDDWWWWWWWWWWWWYYYYYYYYYbbbbbbbyyyyyyy______.',
  '.................................FFFBBBBBBBDDDDDDDWWWWWWWWWWWWYYYYYYYYYbbbbyyyyyyyyyy______.',
  '..............................FFFFFFBBBBBBBBDDDDDDWWWWWWWWWWWWWWWbbbbyyyyyyyyyyyyyyyyy_____.',
  '...........................FFFFFFFFFFBBBBBBBDDDDDDDWWWWWWWWWWWWWyyyyyyyyyyyyyyyyyyyyyy_____.',
  '..........................FFFFFFFFFFFBBBFuuuuDDDDDDWWWWWWWWWWWWWyyyyyyyyyyyyyyyyyyyyyyy____.',
  '.........................FFFFFFFFFFFFFFFFuuuuDDDDDDWWWWWWWWWWWWWyyyyyyyyyyyyyyeeeyyyyyy____.',
  '........................FFFFFFFFFFFFFFFFFuuuuDDDDDDCCCCCWWWWkkkkkyyyyyyyyyyyeeeeeyyyyy_____.',
  '.......................FFFFFFFFFFFFFFFFFFFDDDDCCCCCCCCCCkkkkkkkkkyyyyyyyyyyyeeeeeyyyy______.',
  '.......................FFFFFFFFFFFFFFFFFFFDDDDCCCCCCCCCCkkkkkkkkk_yyyyyyyyyyeeeeeyyy_______.',
  '.......................FFFFFFFFFFFFFFFFFFFFDDDCCCCCCCCCCkkkkkkkkkk_yyyyRRRReeeeeeyy________.',
  '.......................FFFFFFFFFFFFFFFFFFFFF_DCCCCCCCCCCCkkkkkkkkkRRRRRRRRReeeeeey_________.',
  '.......................FFFFFFFFFFFFFFFFFFFFF__CCCCCCCCCC_kkkkHHHHHRRRRRRRRReeeR..._________.',
  '........................FFFFFFFFFFFFFFFFFFFFiii__CCAAAAAHHHHHHHHHHRRRRRRRRRRRRR..._________.',
  '........................FFFFFFFFFFFFFFFFFZZiiiiiAAAAAAAAHHHHHHHHHHRRRRRRRRRRRRR....________.',
  '........................FFFFFFFFFFFFFFZZZZZZiiiAAAAAAAAAHHHHHHHHHHHRRRRRRRRRRRRR...________.',
  '........................FFFFFFFFFFFFFFZZZZZZZAAAAAAAAnnnnHHQQQQrrrrrrrrRRRRRRRR....________.',
  '.........................aaaaFFFFFFFFFZZZZZZZZAXXXnnnnnnnQQQQQQQrrrrrrrRRRRRRR......_______.',
  '.........................aaaaEEFFFFFFFFZZZXXXXXXXXnnnnnnnnQQQQQQrrrrrrrRRRRRR...............',
  '.................EEEEEEEEaaaaEEEFFFFFFFZZZXoooXXXXXnnnnnnnQQQQQQQrrrrrrRRRRGGGGGG...........',
  '.............EPPPEEEEEEEEEEEEEEEEFF.......oooooXXXXnnn..QQQQQhhhQrrrrrrrGGGGGGGGG...........',
  '............PPPPPEEEEEEEEEEEEEEEEE.........oooXXXXXXXX..QQhhhhhhQQrrrrrrGGGGGGGGG...........',
  '............PPPPPEEEEEEEEEEEEEEEEE.........XXXXXXXXXX....QhhhhhhQxxxxxrrGGGGGGGGG...........',
  '............PPPPPEEEEEEEEEEEEEEEE............XXXXXXXXX....hhhhhh_xxxxx_GGGGGGGGGGG..........',
  '............PPPPPEEEEEEEEEEEEEEEE.............XXXXXsss....hhhhhh_xxxxx_GGGGGGGGGGG..........',
  '............PPPPPEEEEEEEEEEEEEEEE..............XXXsssss....hhhmmmxxxdddGGGGGGGGGGG..........',
  '............PPPPPEEEEEEEEEEEEEEE................XXXsssX....hmmmmmdddddd.GGGGGGG.............',
  '............PPPPPEEEEEEEEEEEEEEE.................XXXXXX....hmmmlldddddd.GG..................',
  '............PPPPPEEEEEEEEEEEEEEE..................vvvXXX....mlllldddddd.................___.',
  '............PPPPPEEEEEEEEEEEEEE..................vvvvvXXX....llll.ddddd..........__________.',
  '............PPPPPEEEEEEEEEEEEE....................vvvXXXXX...llll.dd.......________________.',
  '............PPPPPEEEEEEEEEEEE.............XX........XXXXXXX..llll.......___________________.',
  '............PPPPPEEEEEEEEEEE............XXXX.........XXXXXXX.llll....gg____________________.',
  '............PPPPPEEEEEEEEEE.............XXXX.........XXXXXXX.lllgggggggg___________________.',
  '............PPPPPEEEEEEEEE..............XXXXX.........XXXXX...gggggggggg___________________.',
  '.................EEEE....................XXXX..........X......ggggggggggg__________________.',
  '.........................................XX..........X........gggggggggg.._________.........',
  '....................................................XX........ggggggg.......................',
  '...............................................XXXXXXX........gggggg............cccccc......',
  '..............................................XXXXXXX........gggggggg...........cccccc......',
  '.................................................XXXX........gggggggg...........cccccc......',
  '.............................................................ggggggggg......................',
  '..............................................................ggggggg.......................',
  '.................................................tttt...........gg..........................',
  '.................................................tttt.......................................',
  '.................................................tttt.......................................',
  '............................................................................................',
  '............................................................................................'
];

const WORLD_W = 92 * MAP_SCALE;
const WORLD_H = 76 * MAP_SCALE;
